### ISSUE TITLE
Fabric API 0.60.0 - crash

### ISSUE THREAD

**Issue by Romz24** [Globox1997/AdventureZ#117]
After I updated the Fabric API version 0.59.0 to 0.60.0, I get a crash when starting the game. Is it related to your mod, can you fix it?

Mod version: **1.4.14**
Fabric API: **0.60.0** _(Version 0.59.0 causes no problems)_
Fabric loader: **0.14.9**
Game version: **1.19.2**

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'adventurez'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$dkf000$catchFabricInit(class_310.java:19954)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/object/builder/SpawnRestrictionAccessor
	at net.adventurez.init.SpawnInit.setSpawnRestriction(SpawnInit.java:45)
	at net.adventurez.init.SpawnInit.init(SpawnInit.java:19)
	at net.adventurez.AdventureMain.onInitialize(AdventureMain.java:20)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.object.builder.SpawnRestrictionAccessor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more
```

**Comment by Globox1997** [comment]
Updated to 1.19.2 with [https://github.com/Globox1997/AdventureZ/commit/bea1933e568a8e242c212b10801c9c34a48fa3a5](https://github.com/Globox1997/AdventureZ/commit/bea1933e568a8e242c212b10801c9c34a48fa3a5) which will fix the issue

**Comment by Romz24** [comment]
When will this be published on curseforge?

**Comment by Globox1997** [comment]
Probably tomorrow
